# Generated by Django 6.0.1 on 2026-01-23 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GICSIndustryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GICSSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ISICIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ISICIndustryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ISICSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(blank=True, choices=[('up', 'Higher is better'), ('down', 'Lower is better'), ('target', 'Closer to target is better')], max_length=10, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GICSIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('industry_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industries', to='kpi_app.gicsindustrygroup')),
            ],
        ),
        migrations.AddField(
            model_name='gicsindustrygroup',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industry_groups', to='kpi_app.gicssector'),
        ),
        migrations.CreateModel(
            name='GICSSubIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subindustries', to='kpi_app.gicsindustry')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('gics_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi_app.gicsindustry')),
                ('isic_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi_app.isicindustry')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('gics_industry_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi_app.gicsindustrygroup')),
                ('isic_industry_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi_app.isicindustrygroup')),
            ],
        ),
        migrations.AddField(
            model_name='isicindustry',
            name='industry_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industries', to='kpi_app.isicindustrygroup'),
        ),
        migrations.AddField(
            model_name='isicindustrygroup',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industry_groups', to='kpi_app.isicsector'),
        ),
        migrations.CreateModel(
            name='ISICSubIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subindustries', to='kpi_app.isicindustry')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('gics_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi_app.gicssector')),
                ('isic_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi_app.isicsector')),
            ],
        ),
        migrations.CreateModel(
            name='Subindustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('gics_sub_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi_app.gicssubindustry')),
                ('isic_sub_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi_app.isicsubindustry')),
            ],
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geography', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('value_type', models.CharField(blank=True, max_length=50, null=True)),
                ('value_low', models.FloatField(blank=True, null=True)),
                ('value_high', models.FloatField(blank=True, null=True)),
                ('source', models.URLField(blank=True, null=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi_app.industry')),
                ('industry_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi_app.industrygroup')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.kpi')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi_app.sector')),
                ('sub_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi_app.subindustry')),
            ],
        ),
        migrations.CreateModel(
            name='KPIIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.industry')),
                ('industry_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.industrygroup')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.kpi')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.sector')),
                ('sub_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.subindustry')),
            ],
            options={
                'unique_together': {('kpi', 'sub_industry')},
            },
        ),
    ]
